import {promptTemplates} from '../public/prompt-kit.mjs';
import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {curated,escapeHTML as e} from '../public/catalog.mjs';
import {workflows,guides} from '../public/content.mjs';
import {missions} from '../public/discovery.mjs';
import {renderRoute} from '../public/views.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const items=[...curated,...JSON.parse(await readFile(path.join(root,'public/imported.json'),'utf8'))];
const template=await readFile(path.join(root,'public/index.html'),'utf8');
const routes=[...promptTemplates.map(p=>'/prompts/'+p.id),'/repositories','/power-map','/collections',...['agents','design','marketing','video','product','automation'].map(id=>'/collections/'+id),'/planner','/prompts','/hq','/shared','/missions','/stacks',...missions.map(m=>'/missions/'+m.id),...missions.filter(m=>m.steps).map(m=>'/stacks/'+m.id),'/','/directory','/saved','/finder','/compare','/workflows','/learn','/training','/workshops','/coaching','/security','/inspector','/contact','/submit','/support','/privacy','/terms','/disclosure','/credits',...items.map(x=>'/tools/'+x.id),...workflows.map(x=>'/workflows/'+x.id),...guides.map(x=>'/guides/'+x.id)];
await rm(path.join(root,'dist'),{recursive:true,force:true});await cp(path.join(root,'public'),path.join(root,'dist'),{recursive:true});
const clean=s=>s.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
for(const route of [...routes,'/404']){const content=renderRoute(route,items,{saved:[],compare:[]});const title=clean(content.match(/<h1[^>]*>([\s\S]*?)<\/h1>/)?.[1]||'Discover your next superpower');const tool=items.find(x=>route==='/tools/'+x.id);const description=tool?.description||'Discover useful AI tools and build your superpowers through practical training, workshops and coaching from Waymaker.';let html=template.replace('<!--APP-->',content).replace(/<title>.*?<\/title>/,`<title>${e(title)} — Superpowers by Waymaker</title>`).replace(/<meta name="description"[^>]+>/,`<meta name="description" content="${e(description)}"><meta property="og:title" content="${e(title)} — Superpowers"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="website">`);const folder=path.join(root,'dist',route);await mkdir(folder,{recursive:true});await writeFile(path.join(folder,'index.html'),html)}
await writeFile(path.join(root,'dist/routes.json'),JSON.stringify(routes));
const origin='https://superpowers-complete-production.up.railway.app';
await writeFile(path.join(root,'dist/sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.filter(r=>!['/saved','/compare','/hq','/shared'].includes(r)).map(r=>'<url><loc>'+origin+r+'</loc></url>').join('')+'</urlset>');
await writeFile(path.join(root,'dist/robots.txt'),'User-agent: *\nAllow: /\nDisallow: /saved\nDisallow: /hq\nDisallow: /shared\nDisallow: /compare\nSitemap: https://superpowers-complete-production.up.railway.app/sitemap.xml\n');
console.log(`Built ${routes.length} rendered pages with ${items.length} tools, ${workflows.length} routines and ${guides.length} lessons.`);
