import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {curated,searchTools} from '../public/catalog.mjs';
import {renderRoute} from '../public/views.mjs';
import {workflows,guides} from '../public/content.mjs';
import {createServer} from '../server.mjs';
const imported=JSON.parse(await readFile(new URL('../public/imported.json',import.meta.url),'utf8'));
const items=[...curated,...imported];
test('catalog records have unique IDs, sources, honest evidence labels and routable links',()=>{assert.equal(items.length,500);assert.equal(new Set(items.map(t=>t.id)).size,500);for(const t of items){assert.match(t.id,/^[a-z0-9-]+$/);assert.equal(new URL(t.url).protocol,'https:');assert.equal(new URL(t.sourceUrl).protocol,'https:');assert.ok(t.description);assert.equal(t.tested,false);assert.ok(['Documentation reviewed','Community listing'].includes(t.status))}assert.equal(curated.length,13)});
test('search, role, type and review filters intersect and reset correctly',()=>{assert.ok(searchTools(items,{query:'figma',role:'Designers',reviewed:true}).some(t=>t.id==='figma'));assert.equal(searchTools(items,{type:'Plugins',reviewed:true}).length,1);assert.equal(searchTools(items,{query:'no-match-zzzz'}).length,0);assert.equal(searchTools(items,{savedOnly:true,saved:['figma','notion']}).length,2);assert.ok(searchTools(items,{role:'Developers'}).every(t=>t.roles.includes('Developers')));assert.equal(searchTools(items,{reviewed:true}).length,13)});
test('every workflow resolves its tools and contains an actionable review step',()=>{assert.equal(workflows.length,12);assert.equal(guides.length,6);for(const w of workflows){assert.ok(w.tools.every(id=>curated.some(t=>t.id===id)));assert.equal(w.steps.length,3);assert.ok(w.prompt&&w.review&&w.output)}});
test('untrusted query and catalog strings are escaped in rendered HTML',()=>{const attack='<img src=x onerror=alert(1)>';assert.ok(!renderRoute('/directory?role='+encodeURIComponent(attack),items).includes(attack));assert.ok(!renderRoute('/contact?topic='+encodeURIComponent(attack),items).includes(attack));const evil={...curated[0],id:'malicious',name:attack,description:attack,publisher:attack};const html=renderRoute('/tools/malicious',[evil]);assert.ok(!html.includes(attack));assert.ok(html.includes('&lt;img'))});
test('public pages are rendered without JavaScript and do not imply live inspection',async()=>{const index=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');assert.ok(index.includes('Everyday you.<br><em>Extraordinary'));assert.ok(index.includes('Training'));const detail=await readFile(new URL('../dist/tools/figma/index.html',import.meta.url),'utf8');assert.ok(detail.includes('Figma MCP'));assert.ok(detail.includes('Not connection-tested'));const demo=renderRoute('/inspector',items);assert.ok(demo.includes('Demo only'));assert.ok(!demo.includes('type="password"'))});
test('HTTP serves real pages, enforces methods, handles missing paths and excludes source files',async()=>{const server=createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;try{let r=await fetch(base+'/health');assert.equal(r.status,200);assert.equal((await r.json()).status,'ok');r=await fetch(base+'/tools/figma');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/object-src 'none'/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');assert.ok((await r.text()).includes('Figma MCP'));r=await fetch(base+'/server.mjs');assert.equal(r.status,404);r=await fetch(base+'/no-such-page');assert.equal(r.status,404);r=await fetch(base+'/imported.json',{method:'POST'});assert.equal(r.status,405);r=await fetch(base+'/%00');assert.equal(r.status,400);r=await fetch(base+'/assets/hero.webp',{method:'HEAD'});assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/webp');assert.equal(await r.text(),'')}finally{await new Promise(resolve=>server.close(resolve))}});

test('missions, power stacks and category discovery resolve tools and render usable pages',async()=>{const {missions}=await import('../public/discovery.mjs');assert.equal(missions.length,30);assert.equal(missions.filter(x=>x.steps).length,20);for(const m of missions){assert.ok(renderRoute('/missions/'+m.id,items).includes(m.title));if(m.steps){assert.equal(m.steps.length,3);assert.ok(m.tools.every(id=>curated.some(t=>t.id===id)));assert.ok(renderRoute('/stacks/'+m.id,items).includes('Your human checkpoint'))}}const rows=searchTools(items,{category:'Marketing'});assert.ok(rows.length);assert.ok(rows.every(x=>x.category==='Marketing'));assert.ok(renderRoute('/directory?category=Marketing',items).includes('Power category'));assert.ok(renderRoute('/stacks',items).includes('20 guided starting points'))});
test('share links allow only known tool IDs and progress discards invalid records',async()=>{const {parseSharedTools,cleanProgress}=await import('../public/power-state.mjs');const {missions}=await import('../public/discovery.mjs');assert.deepEqual(parseSharedTools('figma,unknown,figma,notion,<script>',items),['figma','notion']);assert.deepEqual(cleanProgress({prototype:[0,0,3,4,-1,'1'],unknown:[0]},missions),{prototype:[0,3]});const html=renderRoute('/shared?tools=figma,notion,unknown',items);assert.ok(html.includes('Save these 2 tools'));assert.ok(!html.includes('data-save="unknown"'));assert.ok(renderRoute('/hq',items,{saved:['figma'],progress:{prototype:[0]}}).includes('1 of 4 checkpoints complete'));assert.ok(renderRoute('/stacks/prototype',items,{progress:{prototype:[0]}}).includes('data-progress="prototype:0" checked'))});

test('planner explains matches and prompts respect role and search filters',async()=>{const {findMissions}=await import('../public/planner.mjs');const {missions}=await import('../public/discovery.mjs');assert.ok(findMissions(missions,'build a website','Designers').matches.some(x=>x.mission.id==='prototype'));assert.ok(findMissions(missions,'investigate a bug','Developers').matches.some(x=>x.mission.id==='debug'));assert.equal(findMissions(missions,'zzqxx', 'All').matches.length,0);assert.ok(findMissions(missions,'campaign','Marketers').matches.every(x=>x.mission.role==='Marketers'));assert.ok(renderRoute('/planner?goal=website',items).includes('Why this appeared:'));assert.ok(renderRoute('/prompts?query=prototype',items).includes('1 prompts for you'));assert.ok(!renderRoute('/planner?goal=%3Cscript%3E',items).includes('<script>'))});

test('catalog refresh preserves typed drafts, selected roles, checkboxes and cursor',async()=>{const {captureInputs,restoreInputs}=await import('../public/input-state.mjs');const doc={activeElement:null};const control=(id,type,value)=>({id,name:id,type,value,checked:false,ownerDocument:doc,selectionStart:null,selectionEnd:null,focus(){doc.activeElement=this},setSelectionRange(a,b){this.selectionStart=a;this.selectionEnd=b}});const old=[control('goal','text','Build a website'),control('role','select-one','Designers'),control('checkpoint','checkbox','on')];old[2].checked=true;doc.activeElement=old[0];old[0].selectionStart=6;old[0].selectionEnd=6;const draft=captureInputs({querySelectorAll:()=>old});const fresh=[control('goal','text',''),control('role','select-one','All'),control('checkpoint','checkbox','on')];restoreInputs({querySelectorAll:()=>fresh},draft);assert.equal(fresh[0].value,'Build a website');assert.equal(fresh[1].value,'Designers');assert.equal(fresh[2].checked,true);assert.equal(doc.activeElement,fresh[0]);assert.equal(fresh[0].selectionStart,6)});
