import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {randomUUID} from 'node:crypto';
import {validateSubmission,serviceResults} from '../public/submissions.mjs';
import {submissionRequest,createLimiter,saveSubmission} from '../submission-api.mjs';
import {createServer} from '../server.mjs';
const fixture=()=>({kind:'service',name:'Example studio',website:'https://example.com/',description:'Synthetic example of an AI workflow consulting service.',category:'AI strategy & consulting',contact_name:'Example tester',contact_email:'qa@example.invalid',consent:true,request_id:randomUUID()});
test('submissions enforce consent, safe URLs and categories without accepting review fields',()=>{assert.deepEqual(validateSubmission(fixture()).errors,[]);for(const website of ['javascript:alert(1)','http://example.com','https://name:secret@example.com','https://localhost'])assert.ok(validateSubmission({...fixture(),website}).errors.length);assert.ok(validateSubmission({...fixture(),consent:false}).errors.length);assert.ok(validateSubmission({...fixture(),category:'made up'}).errors.length);assert.ok(validateSubmission({...fixture(),company_fax:'spam'}).errors.length);assert.equal(validateSubmission({...fixture(),status:'accepted',review_notes:'fake'}).data.status,undefined);});
test('service directory escapes submitted content and rejects unsafe outbound links',()=>{const html=serviceResults([{name:'<script>alert(1)</script>',description:'<img src=x>',category:'Coaching',website:'javascript:alert(1)'}]);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('href="javascript:'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(serviceResults([]).includes('taking shape'));});
test('intake blocks cross-site posts, oversized payloads and honest storage failures',async()=>{const req=(body,headers={})=>Object.assign(Readable.from([body]),{headers:{'content-type':'application/json',...headers}});assert.equal((await submissionRequest(req(JSON.stringify(fixture()),{'sec-fetch-site':'cross-site'}))).status,403);assert.equal((await submissionRequest(req('x'.repeat(16001)))).status,413);assert.equal((await submissionRequest(req('{bad'))).status,400);assert.equal((await submissionRequest(req(JSON.stringify(fixture())),{save:async()=>{throw Error('fail')}})).status,503);});
test('HTTP intake stores a pending submission and returns a reference only after storage succeeds',async()=>{let saved;const server=createServer({saveSubmission:async data=>{saved=data}});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const input={...fixture(),status:'accepted',review_notes:'not allowed'},url='http://127.0.0.1:'+server.address().port;const response=await fetch(url+'/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});assert.equal(response.status,201);assert.equal((await response.json()).reference,input.request_id);assert.equal(saved.id,input.request_id);assert.equal(saved.status,undefined);assert.equal(saved.review_notes,undefined);assert.equal(saved.contact_email,'qa@example.invalid');assert.equal((await fetch(url+'/api/submissions')).status,404);}finally{await new Promise(r=>server.close(r));}});
test('rate limiter is bounded per window and expires',()=>{const allow=createLimiter();assert.equal(allow('email',2,0),true);assert.equal(allow('email',2,0),true);assert.equal(allow('email',2,0),false);assert.equal(allow('email',2,3600001),true);});

test('storage retries acknowledge only a duplicate reference, never other database errors',async()=>{const options={base:'https://example.supabase.co',key:'publishable-test',fetcher:async()=>({ok:false,status:409,json:async()=>({code:'23505'})})};await saveSubmission(fixture(),options);await assert.rejects(()=>saveSubmission(fixture(),{...options,fetcher:async()=>({ok:false,status:403,json:async()=>({code:'42501'})})}));});
